### ISSUE TITLE
mac 执行安装提示操作

### ISSUE THREAD

**Issue by muyichuanqi** [laoyin/freeswitch_docker_file#1]
> ERROR [12/18] RUN cd /usr/src/libs/spandsp && ./bootstrap.sh && ./configure CFLAGS="-g -ggdb" --with-pic --prefix=/usr && make -j`nproc  1.9s
------
 > [12/18] RUN cd /usr/src/libs/spandsp && ./bootstrap.sh && ./configure CFLAGS="-g -ggdb" --with-pic --prefix=/usr && make -j`nproc --all` && make install:
#15 0.184 mkdir: cannot create directory 'config': File exists
#15 1.840 configure.ac:21: error: Autoconf version 2.71 or higher is required
#15 1.840 configure.ac:21: the top level
#15 1.841 autom4te: /usr/bin/m4 failed with exit status: 63
#15 1.844 aclocal: error: /usr/bin/autom4te failed with exit status: 63
#15 1.852 autoreconf: aclocal failed with exit status: 63
#15 1.855 /bin/sh: 1: ./configure: not found

**Comment by muyichuanqi** [comment]
试了一下 ubantu 中通过 docker 安装也是不行

**Comment by laoyin** [comment]
试试最新的dockerfile， 原因是官方最新代码和 spandsp代码有bug @muyichuanqi
