### ISSUE TITLE
dockerfile 执行到最后一个make报错

### ISSUE THREAD

**Issue by m4ak** [laoyin/freeswitch_docker_file#2]
120.2 make[4]: *** [Makefile:770: mod_spandsp_la-mod_spandsp_dsp.lo] Error 1
120.2 make[4]: Leaving directory '/usr/src/freeswitch/src/mod/applications/mod_spandsp'
120.2 make[3]: *** [Makefile:728: mod_spandsp-all] Error 1
120.2 make[3]: *** Waiting for unfinished jobs....
120.2   CC       mod_conference_la-conference_utils.lo
120.3   CC       mod_conference_la-conference_file.lo
120.7   CC       libsofiamod_la-sofia.lo
120.7   CC       mod_conference_la-conference_record.lo
120.8   CC       test/test_image-test_image.o
121.3   CCLD     libmodconference.la
121.4   CCLD     mod_conference.la
121.7   CCLD     test/test_member
122.1   CCLD     test/test_image
122.3   CC       libsofiamod_la-sofia_json_api.lo
122.3   CC       test/test_mod_lua-test_mod_lua.o
122.6 make[4]: Leaving directory '/usr/src/freeswitch/src/mod/applications/mod_conference'
122.6   CXXLD    libluamod.la
122.8   CC       libsofiamod_la-sofia_glue.lo
122.8   CXXLD    mod_lua.la
123.2   CC       libsofiamod_la-sofia_presence.lo
123.5   CCLD     test/test_mod_lua
124.1 make[4]: Leaving directory '/usr/src/freeswitch/src/mod/languages/mod_lua'
124.1   CC       libsofiamod_la-sofia_reg.lo
125.5   CC       libsofiamod_la-sofia_media.lo
125.9   CC       libsofiamod_la-sip-dig.lo
126.2   CC       libsofiamod_la-rtp.lo
126.8   CC       test/test_nuafail-test_nuafail.o
126.9   CC       test/sipp_based_tests-sipp-based-tests.o
127.0   CC       test/test_sofia_funcs-test_sofia_funcs.o
131.8   CCLD     libsofiamod.la
132.0   CCLD     mod_sofia.la
132.0   CCLD     test/test_sofia_funcs
132.0   CCLD     test/test_nuafail
132.0   CCLD     test/sipp-based-tests
132.6 make[4]: Leaving directory '/usr/src/freeswitch/src/mod/endpoints/mod_sofia'
132.6 make[3]: Leaving directory '/usr/src/freeswitch/src/mod'
132.6 make[2]: *** [Makefile:630: all-recursive] Error 1
132.6 make[2]: Leaving directory '/usr/src/freeswitch/src'
132.6 make[1]: *** [Makefile:3715: all-recursive] Error 1
132.6 make[1]: Leaving directory '/usr/src/freeswitch'
132.6 make: *** [Makefile:1437: all] Error 2
------
Dockerfile:54
--------------------
  52 |     RUN cd /usr/src/freeswitch && ./bootstrap.sh -j

  53 |     RUN cd /usr/src/freeswitch && ./configure

  54 | >>> RUN cd /usr/src/freeswitch && make -j`nproc` && make install

  55 |     

  56 |     # Cleanup the image

--------------------
ERROR: failed to solve: process "/bin/sh -c cd /usr/src/freeswitch && make -j`nproc` && make install" did not complete successfully: exit code: 2

放上来的错误日志中上面关于spandsp有报错了，现在用Debian10 单独执行命令，看看是不也是spandsp这里出错。

**Comment by laoyin** [comment]
测试过了，fs代码和 spandsp 代码有bug。 已经更新最新dockerfile，我测试了ok。

**Comment by DotNeter-Hpf** [comment]
太感谢了，我也遇到了这个问题，已经构建成功
