### ISSUE TITLE
git clone 一直提示超时

### ISSUE THREAD

**Issue by DotNeter-Hpf** [laoyin/freeswitch_docker_file#3]
请问有好的解决办法吗，我想手动下载扔到对应位置

**Comment by DotNeter-Hpf** [comment]
<img width="1561" alt="image" src="https://github.com/laoyin/freeswitch_docker_file/assets/62707731/e0952932-94bb-46e2-a788-9969188a95d8">

**Comment by laoyin** [comment]
加代理吧，或者本地clone之后， dockerfile cp 进去
